pom.xml

closes keycloak/keycloak#31262

Remove FIPS profiles from pom.xml

---

admin-client-jee/pom.xml
admin-client/pom.xml
authz-client/pom.xml
pom.xml

Latest keycloak-client failed to compile

---

pom.xml

Remove some unused dependencies and versions from top pom.xml

---

client-common-synced/pom.xml
client-common-synced/src/main/java/org/keycloak/protocol/oidc/representations/MTLSEndpointAliases.java
client-common-synced/src/main/java/org/keycloak/protocol/oidc/representations/OIDCConfigurationRepresentation.java

Add missing classes by keycloak-authorization extension of Quarkus

---

testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/AbstractResourceServerTest.java
testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/PermissionManagementTest.java
testsuite/authz-tests/src/test/resources/authorization-test/default-keycloak-uma2.json
testsuite/framework/src/main/java/org/keycloak/client/testsuite/common/RealmImporter.java

Closes #65
Another class moved. I have just added one because the next classes are going to be complicated.

Move PermissionManagementTest to keycloak-client

---

client-common-synced/pom.xml
client-common-synced/src/main/java/org/keycloak/TokenVerifier.java
client-common-synced/src/main/java/org/keycloak/exceptions/TokenNotActiveException.java
client-common-synced/src/main/java/org/keycloak/exceptions/TokenSignatureInvalidException.java
client-common-synced/src/main/java/org/keycloak/exceptions/TokenVerificationException.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/AbstractAdminClientTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/group/AbstractGroupTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/group/GroupMappersTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/group/GroupTest.java
testsuite/admin-client-tests/src/test/resources/testrealm.json
testsuite/framework/src/main/java/org/keycloak/client/testsuite/common/OAuthClient.java
testsuite/framework/src/main/java/org/keycloak/testsuite/util/KeyUtils.java
testsuite/framework/src/main/java/org/keycloak/testsuite/util/KeycloakModelUtils.java

Moved `AbstractGroupTest`, `GroupTest`, `GroupMappersTest` to keycloak-client
Closes #42

Move AbstractGroupTest, GroupTest, GroupMappersTest to keycloak-client

---

testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/AbstractAdminClientTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/client/AbstractClientTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/client/AbstractProtocolMapperTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/client/ClientProtocolMapperTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/client/ClientRolesTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/client/ClientScopeProtocolMapperTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/client/ClientScopeTest.java

Moved `AbstractClientTest, AbstractProtocolMapperTest, ClientProtocolMapperTest, ClientRolesTest, ClientScopeProtocolMapperTest, ClientScopeTest` to keycloak-client
Closes #44

Move client tests to keycloak-client

---

testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/UsersTest.java

Move UsersTest

---

.github/workflows/ci.yml

Test with Keycloak 26 server

---

docs/guides/attributes.adoc
docs/guides/securing-apps/authz-client.adoc

Add back documentation for client authentication for authz client

---

client-common-synced/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java

Sync with keycloak server 26.0.4

---

policy-enforcer/src/main/java/org/keycloak/adapters/authorization/PathConfigMatcher.java

Fixes https://github.com/keycloak/keycloak-client/issues/113

Fix wrong logger class for PathConfigMatcher

---

.github/workflows/ci.yml
.github/workflows/schedule-sync-nightly.yml

Remove JEE from the title of GH actions

---

.github/workflows/sync-and-send-pr.yml

Add signature to the commit when sync with keycloak server

---

.github/workflows/ci.yml

Test with keycloak server images 24.0, 26.0 and 26.1

---

pom.xml

Fixes https://github.com/keycloak/keycloak-client/issues/150.

Fix SCM URLs in POM

---

docs/release-notes/26_0_0.adoc

Add release notes for seperate versioning announcement

---

.github/workflows/sync-and-send-pr.yml

Closes #134
I should have managed to automate everything.
Here’s an example on my fork showing how it should look: [issue](https://github.com/graziang/keycloak-client/issues/37) and [PR](https://github.com/graziang/keycloak-client/pull/38)

Create issue before sending sync PR

---

testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/RealmTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/UserTest.java
testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/RequiredActionsTest.java

Fix keycloak-client ci with nightly build

---

.github/workflows/release.yml
admin-client/pom.xml
policy-enforcer/pom.xml
testsuite/admin-client-tests/pom.xml
testsuite/authz-tests/pom.xml
testsuite/framework/pom.xml
testsuite/pom.xml
testsuite/providers/pom.xml

Backport fixes related to switching to Central Publishing Maven Plugin

---

README.md
RELEASE-CHECKLIST.md

Update RELEASE-CHECKLIST.md and README.md files

---

docs/guides/securing-apps/upgrading.adoc

Fixing a broken anchor when rendering in keycloak-web and downstream

---

policy-enforcer/src/main/java/org/keycloak/adapters/authorization/PathConfigMatcher.java
testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/policyenforcer/PolicyEnforcerTest.java
testsuite/authz-tests/src/test/resources/authorization-test/enforcer-max-entries.json

Allow resolving matching resources on the server
