keycloak/keycloak-client

policy-enforcer/pom.xml
closes keycloak/keycloak#31263
This is related to the PR https://github.com/keycloak/keycloak/pull/31361 and is supposed to be merged together with that.
=> Make policy-enforcer working with suffix added in keycloak repository

authz-client/pom.xml
closes keycloak/keycloak#31264
This is related to the PR https://github.com/keycloak/keycloak/pull/31371 and should be merged together with that one.
=> Make authz-client working with suffix added in keycloak repository

.github/workflows/ci.yml, pom.xml
Adds a workflow that builds the artifacts in the repository with a `nightly` profile that pulls the latest snapshot artifacts of Keycloak from the Sonatype staging repository.
=> Add GitHub workflow to build with Keycloak Nightly

testsuite/authz-tests/pom.xml, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/policyenforcer/ClaimInformationPointProviderTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/policyenforcer/PolicyEnforcerClaimsTest.java, testsuite/pom.xml
closes keycloak/keycloak#31981
closes keycloak/keycloak#31982
- Adding dependency on undertow to the testsuite (Used by `ClaimInformationProviderTest` for provisioning of simple HTTP server where the HTTP based claims information point is provided)
=> Move PolicyEnforcerClaimsTest and ClaimInformationProviderTest

.github/env/release-env, .github/mvn-rel-settings.xml, .github/workflows/release-nightly.yml, .github/workflows/release.yml, .github/workflows/x-create-tags.yml, .github/workflows/x-env.yml, .github/workflows/x-keycloak-client.yml, set-version.sh, testsuite/admin-client-tests/pom.xml, testsuite/authz-tests/pom.xml, testsuite/framework/pom.xml, testsuite/pom.xml
=> Setting up release workflows for keycloak-client project.

pom.xml
Closes #39
Just updating the quarkus dependencies to be the same versions used in keycloak project.
=> Aling quarkus deps to 3.13.x as keycloak

admin-client/pom.xml, authz-client/pom.xml, docs/guides/pom.xml, docs/maven-plugin/pom.xml, docs/pom.xml, policy-enforcer/pom.xml, pom.xml, set-version.sh, testsuite/admin-client-tests/pom.xml, testsuite/authz-tests/pom.xml, testsuite/framework/pom.xml, testsuite/pom.xml, testsuite/providers/pom.xml
closes #15
Since we have alpha release already, it's possibly good time to make snapshot versions aligned with the same versions as used by Keycloak codebase.
=> Update snapshot version to 999.0.0-SNAPSHOT similarly like Keycloak has

testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/AbstractAuthzTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/AuthorizationAPITest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/AuthorizationTest.java, testsuite/authz-tests/src/test/resources/authorization-test/default-keycloak-pairwise.json, testsuite/authz-tests/src/test/resources/authorization-test/default-keycloak.json, testsuite/framework/src/main/java/org/keycloak/client/testsuite/framework/PairwiseHttpServerExtension.java
Closes #46
Just the two first authz classes moved from keycloak to keycloak-client. These two have no issues at all. Only that the API one uses a pairwise mapper that needs an HTTP server to download the redirect URIs. I have just added a simple extension with fixed data. I tyhin this will be re-used in other tests that use pairwise.
=> Move AuthorizationAPITest and AuthorizationTest to keycloak-client

testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/AuthzClientTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/ClientScopePolicyTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/ConflictingScopePermissionTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/EntitlementAPITest.java, testsuite/authz-tests/src/test/resources/authorization-test/default-keycloak-public-client.json, testsuite/framework/src/main/java/org/keycloak/client/testsuite/common/OAuthClient.java, testsuite/framework/src/main/java/org/keycloak/client/testsuite/framework/PairwiseHttpServerExtension.java, testsuite/framework/src/main/java/org/keycloak/testsuite/util/RealmBuilder.java
Closes #59
More tests for the authz-client. `AuthzClientTest`, `ClientScopePolicyTest` and `ConflictingScopePermissionTest` have nothing special. But `EntitlementAPITest` needs different changes in `OAuthClient` because it needs to login normally using the browser to test public clients. The PR does a very simple modification in the client to allow login a public client using the `OAuthClient` (it uses the http client parsing the form action to do send the post login data). `EntitlementAPITest` also does some little events tests that can be done using database.
=> Move AuthzClientTest, ClientScopePolicyTest, ConflictingScopePermissionTest and EntitlementAPITest to keycloak-client

admin-client/src/main/java/org/keycloak/admin/client/resource/AuthenticationManagementResource.java, admin-client/src/main/java/org/keycloak/admin/client/resource/ClientPoliciesPoliciesResource.java, admin-client/src/main/java/org/keycloak/admin/client/resource/ClientTypesResource.java, admin-client/src/main/java/org/keycloak/admin/client/resource/GroupResource.java, admin-client/src/main/java/org/keycloak/admin/client/resource/IdentityProvidersResource.java, admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMemberResource.java, admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java, admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java, admin-client/src/main/java/org/keycloak/admin/client/resource/RealmResource.java, admin-client/src/main/java/org/keycloak/admin/client/resource/RoleResource.java, admin-client/src/main/java/org/keycloak/admin/client/resource/UserResource.java, client-common-synced/src/main/java/org/keycloak/common/Profile.java, client-common-synced/src/main/java/org/keycloak/common/profile/PropertiesProfileConfigResolver.java, client-common-synced/src/main/java/org/keycloak/common/util/MultiSiteUtils.java
closes #57
Running `sync-keycloak-sources.sh` after https://github.com/keycloak/keycloak/pull/32980 added to Keycloak main to update javadoc of the admin-client in the keycloak-client repository.
=> Syncing with keycloak after admin-client javadoc added for compatibility

testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/GroupNamePolicyTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/GroupPathPolicyTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/GroupPathWithoutGroupClaimPolicyTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/PermissionClaimTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/PermissionEqualsTest.java
Closes #62
More tests. No issues this time. The `GroupBuilder` helper class is added for the group tests.
=> Move Group*, PermissionClaimTest and PermissionEqualsTest to keycloak-client

testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/PolicyEvaluationCompositeRoleTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/PolicyEvaluationTest.java
Closes #67
The two test classes PolicyEvaluation* are refactored to use the external authz client instead of internal execution in the server. There is one test that cannot be ported as it is testing the transaction is committed. Probably that class and test should be maintained in keycloak. But all the rest of tests are ported to the keycloak-client.
=> Move PolicyEvaluation* tests to keycloak-client

testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/AbstractAuthorizationTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/AbstractPolicyManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/AggregatePolicyManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/AuthorizationTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/ClientPolicyManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/ExportAuthorizationSettingsTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/GenericPolicyManagementAdminEventTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/GenericPolicyManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/GroupPolicyManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/ImportAuthorizationSettingsTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/JSPolicyManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/ResourceManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/ResourceManagementWithAuthzClientTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/ResourcePermissionManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/ResourceServerManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/RolePolicyManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/ScopeManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/ScopePermissionManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/TimePolicyManagementTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/admin/UserPolicyManagementTest.java, testsuite/authz-tests/src/test/resources/authorization-test/client-with-authz-settings.json, testsuite/authz-tests/src/test/resources/authorization-test/import-authorization-unordered-settings.json, testsuite/framework/src/main/java/org/keycloak/testsuite/util/RealmBuilder.java
Closes #75
Moving all the tests from `authz.admin` package to the keycloak-client. All of them were moved without major issues except `AuthorizationDisabledInPreviewTest` which tests the feature disabled and cannot be done here. With this PR all authz tests have been moved to the client repo.
=> Move tests in package authz.admin tests to keycloak-client

testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/AbstractResourceServerTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/RegexPolicyTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/RolePolicyTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/UmaGrantTypeTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/UmaPermissionTicketPushedClaimsTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/UmaRepresentationTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/UserManagedAccessTest.java, testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/authz/UserManagedPermissionServiceTest.java, testsuite/framework/src/main/java/org/keycloak/client/testsuite/common/OAuthClient.java
More tests for the authz. With this bunch all the `org.keycloak.testsuite.authz` package is finished. No issues except that `UserManagedPermissionServiceTest` needed some refactoring.
Closes #73
=> Move RegexPolicyTest, RolePolicyTest, Uma* and UserManaged* tests to keycloak-client

testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/Assert.java, testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/AbstractAuthenticationTest.java, testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/AuthenticatorConfigTest.java, testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/ExecutionTest.java, testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/FlowTest.java, testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/ProvidersTest.java, testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/RegistrationFlowTest.java, testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/RequiredActionsTest.java, testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/ShiftExecutionTest.java, testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/ShiftRequiredActionTest.java
=> Move authentication tests

.github/workflows/ci.yml, .github/workflows/release-nightly.yml, .github/workflows/schedule-nightly.yml
closes #92
The nightly scheduled is updated to schedule both release and CI.
NOTE: Tests failing because of https://github.com/keycloak/keycloak-client/issues/94
=> Setup CI nightly build

.github/actions/build-keycloak-client/action.yml, .github/actions/build-keycloak/action.yml, .github/actions/pnpm-store-cache/action.yml, .github/actions/test-setup/action.yml, .github/workflows/ci.yml, .github/workflows/sync-and-send-pr.yml
Closes #101
Created a workflow that follows these steps:
- Finds the latest release/* branch in the Keycloak repository.
- Checks out Keycloak with the release branch.
- Build Keycloak.
- Checks out keycloak-client with the main branch.
- Build keycloak-client.
- Synchronizes with Keycloak using the `sync-keycloak-sources.sh` script.
- Exits the workflow if no changes are detected in `client-common-synced`.
- Creates and pushes a new branch named `sync-with-keycloak-server-${release/*}` on the Keycloak repository with the detected changes.
- Creates a pull request from the `sync-with-keycloak-server-${release/*}` branch to main.
I tested the workflow on my fork by modifying the branch in the workflow dispatch:
```yaml
workflow_dispatch:
push:
branches:
- issue-101
```
and setting the …
=> Sync with Keycloak server and send PR

.github/scripts/sync-keycloak-sources.sh, .github/workflows/schedule-sync-nightly.yml
Closes #87
Adding the workflow to execute the sync at night 2.30am. Finally keycloak main is used because the nightly repo seems to not update some packages (the `keycloak-authz-client-tests` is quite old).
=> Setup nightly action to sync from keycloak server main

client-common-synced/pom.xml
Removing `httpclient` dependency
Closes #105
=> Unnecessary httpclient dependency in keycloak-client-common-synced module

testsuite/pom.xml, testsuite/providers/pom.xml, testsuite/providers/src/main/java/org/keycloak/testsuite/events/TestEventsListenerContextDetailsProvider.java, testsuite/providers/src/main/java/org/keycloak/testsuite/events/TestEventsListenerContextDetailsProviderFactory.java, testsuite/providers/src/main/java/org/keycloak/testsuite/events/TestEventsListenerProvider.java, testsuite/providers/src/main/java/org/keycloak/testsuite/events/TestEventsListenerProviderFactory.java, testsuite/providers/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory
closes #109
PR deploys some testsuite providers, so they are available for the server in the testsuite. The provider, which is referenced in the test, caused the test failure.
The keycloak-client should not have any dependency on the Keycloak-server, but it is probably fine to have dependency on the server in the testsuite? Could it be any issue (like productization or something else) why adding dependency on keycloak server artifacts in `testsuite/providers` can cause issues?
=> Add event listener providers

testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/authentication/ProvidersTest.java
closes #115
The `ProvidersTest` might fail quite often as it will always fail with keycloak-server nightly release whenever any new provider is added. Could we be less strict in the client testsuite and just check that all "expected" items are present in the providers, which are returned from server? This means that providers from server can contain some more providers.
This means that `ProviderTest` won't fail always whenever new provider is implemented on the Keycloak server side.
=> ProviderTest failing with latest nightly build

.github/workflows/ci.yml, .github/workflows/sync-and-send-pr.yml
Closes #132
**Pull requests created by a GH action using the default `GITHUB_TOKEN` cannot trigger other workflows like the `ci` workflow.** 
The workaround introduced by this pr is the following: 
- Create draft pull requests, and configure the ci workflow to trigger on: `ready_for_review`. The workflow will run when users manually click the "Ready for review" button on the draft pull requests.
Another approach could have been using a Personal Access Token (PAT) to create the pull request, which is the standard workaround recommended by GitHub. However, it was discarded to avoid introducing PAT management. 
A final test to confirm everything is working correctly can be performed after this PR is merged.
=> Create draft PR to trigger the ci workflow
